name: Check branch convention usage
description: 'Action that checks wether newly created branches follow a naming convention'
author: 'duart38'

branding:
  icon: 'check-circle'
  color: 'gray-dark'

inputs:
  standard_branch_check:
    description: 'Regular expression which shall be used to check if a branch conforms to your standards'
    required: true
  ignore_branch_check:
    description: 'Regular expression to test against and thus ignore a set of branch names'
    required: true
  ignore:
    description: 'Branch names to ignore. Separated via commas'
    required: false
    default: 'main,develop'

runs:
  using: 'node16'
  main: 'dist/index.js'